//
// Generated file, do not edit! Created by nedtool 5.6 from paquete.msg.
//

#ifndef __PAQUETE_M_H
#define __PAQUETE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>paquete.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet CustomPaquete
 * {
 *     int fromSource = false;
 *     int sequenceNumber;
 *     int origin;
 * }
 * </pre>
 */
class CustomPaquete : public ::omnetpp::cPacket
{
  protected:
    int fromSource;
    int sequenceNumber;
    int origin;

  private:
    void copy(const CustomPaquete& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CustomPaquete&);

  public:
    CustomPaquete(const char *name=nullptr, short kind=0);
    CustomPaquete(const CustomPaquete& other);
    virtual ~CustomPaquete();
    CustomPaquete& operator=(const CustomPaquete& other);
    virtual CustomPaquete *dup() const override {return new CustomPaquete(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getFromSource() const;
    virtual void setFromSource(int fromSource);
    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);
    virtual int getOrigin() const;
    virtual void setOrigin(int origin);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CustomPaquete& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CustomPaquete& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PAQUETE_M_H

